apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: loan-servicemonitor
  namespace: library-system

spec:
  selector:
    matchLabels:
      app: loan-service

  namespaceSelector:
    matchNames:
      - library-system

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s