apiVersion: v1
kind: Service

metadata:
  name: loan-service
  namespace: library-system

  labels:
    app: loan-service

spec:

  type: NodePort

  selector:
    app: loan-service

  ports:

    - name: http

      port: 8081

      targetPort: 8081